apiVersion: v1
kind: Service
metadata:
  name: fastapi-file-service
spec:
  selector:
    app: fastapi-file
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Use ClusterIP if it's internal-only
